config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :products do
    resources :cart_items, only: [:create]
    resources :wishlist_items, only: [:create]
  end
  resources :categories

  devise_for :users
  root to: "homes#index"

  resources :user_profiles, only: [:show] 
  post '/shipping_address', to: "user_profiles#shipping_address", only: [:create]
  resources :homes
  resources :carts 

  resources :wishlists
  resources :orders 
  resources :checkouts
  post '/confirm_payment', to: "checkouts#confirm_payment", as: :confirm_payment_checkout
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :cart_items, :dependent => :destroy
	has_many :products, through: :cart_items
	accepts_nested_attributes_for :cart_items, allow_destroy: true

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :product
	belongs_to :cart
	validate :check_quantity
	after_save :update_product_quantity
	
	def total_price
		self.quantity * self.product.price
	end
	
	private
	def check_quantity
		if self.quantity > self.product.quantity
			errors.add("Product is not available for your quantity")
		end
	end

	def update_product_quantity
		# byebug
		if saved_change_to_attribute?(:quantity)
			a = attribute_before_last_save(:quantity)
			b = quantity
			d = self.product.quantity
			c = a.nil? ? b : b - a
			new_quantity = d - c
			self.product.update(quantity: new_quantity) 
		end
	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :products

	scope :main_c, -> { where(category_id: nil) }
	
	has_many :sub_categories, class_name: 'Category'
    belongs_to :category, foreign_key: 'category_id', optional: true
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items
	belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
	after_update :quantity_update
	has_and_belongs_to_many :categories
	has_many :wishlist_items
	has_many :wishlists, through: :wishlist_items
	has_many :cart_items
	has_many :carts, through: :cart_items
	has_many :order_items
	has_many_attached :product_images

	def quantity_update
		if saved_change_to_attribute?(:quantity) && attribute_before_last_save(:quantity) == 0 && quantity > 0
			@wishlists = self.wishlists
      		@wishlists.each do |wishlist|
        		UserMailer.with(user: wishlist.user).wishlist_email.deliver_later
      		end
		end
	end
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_img
  has_one :cart
  has_many :wishlists
  has_many :orders
  has_one :shipping_address
  
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
	belongs_to :user
	has_many :wishlist_items, :dependent => :destroy
	has_many :products, through: :wishlist_items
	accepts_nested_attributes_for :wishlist_items, allow_destroy: true
end

app/models/wishlist_item.rb
class WishlistItem < ApplicationRecord
	belongs_to :product
	belongs_to :wishlist

	def total_price
		self.quantity * self.product.price
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def index   
    end

    def show 
        @cart = current_cart
        @cart_items = @cart.cart_items
    end

    def edit
        @cart = current_cart
    end

    def update
        #byebug
        @cart = current_cart 
        if @cart.update(cart_params)
            redirect_to cart_path
        else
            render :edit
        end
    end


    private
    def cart_params
        params.require(:cart).permit(cart_items_attributes: [:id, :quantity, :_destroy])
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @categories = Category.main_c
    category = Category.find_by(id: params[:category_id])
    @products = category.present? ? category.products : Product.all
    @cart = current_cart
    @wishlist = current_wishlist
    @token = "123asdfd"
  end

  def show
    @product = Product.find_by(id: params[:product_id])
    @cart = current_cart
    @wishlist = current_wishlist
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
    def index 
    end

    def show 
        @wishlist = current_wishlist
        @wishlist_items = @wishlist.wishlist_items
    end

    def edit
        @wishlist = current_wishlist
    end

    def update
        @wishlist = current_wishlist 
        if @wishlist.update(wishlist_params)
            redirect_to wishlist_path
        else
            render :edit
        end
    end

    private
    def wishlist_params
        params.require(:wishlist).permit(wishlist_items_attributes: [:id, :quantity, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/edit.html.erb
<header>
  <%= render 'layouts/navigation' %>
</header>

<div class="card" style="width: 40rem;margin-left: 25rem;">
  <div class="card-body">
    <center><h5 class="card-title">Edit Wishlist</h5></center>
    <%= nested_form_for @wishlist do |form|%>
      <%= form.fields_for :wishlist_items do |f|%>
        <%= f.label f.object.product.name %><br>
        <%= f.label :quantity %>
        <%= f.number_field :quantity %>
        <%= f.link_to_remove "Remove" %>
      <% end %>
      <br>
      <center><%= form.submit %></center>
    <% end %>
  </div>
</div>

app/views/wishlists/show.html.erb
<header>
    <%= render 'layouts/navigation' %>
</header>

<div class="container">
<center>
<h1>Wishlist</h1>
<% if @wishlist_items.empty? %>
  <h4 style="margin-top:3em">Your Wishlist is Empty</h4>
<% else %>
<table class="table table-hover" style="margin-top: 4em;width: 60rem;">
  <thead>
    <tr>
      <th scope="col">Product Name</th>
      <th scope="col">Quantity</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Total Price</th>
      <th scope="col">Available</th>
    </tr>
  </thead>
  <tbody>
    <% @wishlist_items.each do |wishlist|%>
    <tr>
      <td><%= wishlist.product.name %></td>     
      <td><%= wishlist.quantity %></td>
      <td><%= wishlist.product.price %></td>
      <td><%= wishlist.total_price %></td>
      <td>
        <% if wishlist.product.quantity.zero? %>
          <p>Not Available</p>
        <% else%>
          <%= form_with url: product_cart_items_path(:product_id => wishlist.product.id), method: :post do |f| %>              
            <%= f.hidden_field :quantity,value:wishlist.quantity, in: 1..10 %>
            <%= f.submit "Add to Cart" %>
          <% end %>
        <% end %>
      </td>
    </tr>
    <% end %>
    <tr>
      <td colspan="3">Total: </td>
      <td><%= @wishlist_items.map(&:total_price).sum %></td>
    </tr>
  </tbody>
</table>
<%= link_to "Edit Wishlist", edit_wishlist_path, class: "btn btn-outline-success" %>
<% end %>
</center>
</div>