config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :products do
    resources :cart_items, only: [:create]
    resources :wishlist_items, only: [:create]
  end
  resources :categories

  devise_for :users
  root to: "homes#index"

  resources :user_profiles, only: [:show] 
  post '/shipping_address', to: "user_profiles#shipping_address", only: [:create]
  resources :homes
  resources :carts 

  resources :wishlists
  resources :orders 
  resources :checkouts
  post '/confirm_payment', to: "checkouts#confirm_payment", as: :confirm_payment_checkout
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :cart_items, :dependent => :destroy
	has_many :products, through: :cart_items
	accepts_nested_attributes_for :cart_items, allow_destroy: true

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :product
	belongs_to :cart
	validate :check_quantity
	after_save :update_product_quantity
	
	def total_price
		self.quantity * self.product.price
	end
	
	private
	def check_quantity
		if self.quantity > self.product.quantity
			errors.add("Product is not available for your quantity")
		end
	end

	def update_product_quantity
		# byebug
		if saved_change_to_attribute?(:quantity)
			a = attribute_before_last_save(:quantity)
			b = quantity
			d = self.product.quantity
			c = a.nil? ? b : b - a
			new_quantity = d - c
			self.product.update(quantity: new_quantity) 
		end
	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :products

	scope :main_c, -> { where(category_id: nil) }
	
	has_many :sub_categories, class_name: 'Category'
    belongs_to :category, foreign_key: 'category_id', optional: true
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items
	belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
	after_update :quantity_update
	has_and_belongs_to_many :categories
	has_many :wishlist_items
	has_many :wishlists, through: :wishlist_items
	has_many :cart_items
	has_many :carts, through: :cart_items
	has_many :order_items
	has_many_attached :product_images

	def quantity_update
		if saved_change_to_attribute?(:quantity) && attribute_before_last_save(:quantity) == 0 && quantity > 0
			@wishlists = self.wishlists
      		@wishlists.each do |wishlist|
        		UserMailer.with(user: wishlist.user).wishlist_email.deliver_later
      		end
		end
	end
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_img
  has_one :cart
  has_many :wishlists
  has_many :orders
  has_one :shipping_address
  
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
	belongs_to :user
	has_many :wishlist_items, :dependent => :destroy
	has_many :products, through: :wishlist_items
	accepts_nested_attributes_for :wishlist_items, allow_destroy: true
end

app/models/wishlist_item.rb
class WishlistItem < ApplicationRecord
	belongs_to :product
	belongs_to :wishlist

	def total_price
		self.quantity * self.product.price
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def index   
    end

    def show 
        @cart = current_cart
        @cart_items = @cart.cart_items
    end

    def edit
        @cart = current_cart
    end

    def update
        #byebug
        @cart = current_cart 
        if @cart.update(cart_params)
            redirect_to cart_path
        else
            render :edit
        end
    end


    private
    def cart_params
        params.require(:cart).permit(cart_items_attributes: [:id, :quantity, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/layouts/_navigation.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
 <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="/homes">User Dashboard</a>
    <% if user_signed_in? %>
      <%= link_to 'Profile', user_profile_path(current_user), class: "btn btn-outline-success my-2 my-sm-0" %>
      
      <%= link_to 'Cart', cart_path(current_user), class: "btn btn-outline-success btn-space" %>

      <%= link_to 'Wishlist', wishlist_path(current_user), class: "btn btn-outline-success btn-space" %>

      <%= link_to 'My Order', orders_path, class: "btn btn-outline-success btn-space" %>

      <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "btn btn-outline-success btn-logout my-2 my-sm-0" ) %>
      <% if current_user.profile_img.present? %>
        <%= image_tag current_user.profile_img, style: "width:60px;border-radius:50px;margin-left:20rem;" %> 
      <% end %>
    <% else %>
      <%= link_to('Login', new_user_session_path, class: "btn btn-outline-success btn-logout my-2 my-sm-0") %> 
      <%= link_to('SignUp', new_user_registration_path, class: "btn btn-outline-success btn-logout my-2 my-sm-0") %>
    <% end %>
    
  </div>
</nav>

app/views/layouts/_side_navbar.html.erb
<!-- Sidebar -->
<div class="sidebar">
  <a href="#home"><i class="fa fa-fw fa-home"></i> Home</a>
  <a href="#home"><i class="fa fa-fw fa-user"></i>Categories</a>
  <ul>
  <% @categories.each do |category| %>
  
    <%= link_to category.name,homes_path(category_id: category.id) %>
    <ul>
      <% category.sub_categories.each do |sub_cat| %>
        <%= link_to sub_cat.name,homes_path(category_id: sub_cat.id) %>
      <% end %>
    </ul>
  <% end %>
  </ul>
  <% if user_signed_in? %>
    <a href="/orders"><i class="fa fa-fw fa-gift"></i>My Orders</a>
    <%= link_to "My Profile", user_profile_path(current_user),class:"fa fa-user"%>

    <%= link_to 'Change Password', edit_user_password_url(current_user, reset_password_token: @token), class:"fa fa-key"%>
  <% else %>
    <%= link_to('Login', new_user_session_path) %> 
    <%= link_to('SignUp', new_user_registration_path) %>
  <% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcommerceApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    
  </head>

  <body>
    <%= yield %>
    
  </body>
</html>